name: ical4d
description: An ICalendar implementation for Dart.
# version: 1.0.0
# homepage: https://www.example.com
# author: parkjoonyeong <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  optional: ^3.0.0+2
  time_machine: ^0.9.6

dev_dependencies:
  test: ^1.0.0
